name: Product Service CI

on:
  push:
    paths:
      - "microservices/product-service/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build product service
        run: docker build -t product-service ./microservices/product-service

      - name: Run & test
        run: |
          docker run -d -p 5002:5002 product-service
          sleep 5
          curl http://localhost:5002/products
